### ISSUE TITLE
Unable to install using yarn

### ISSUE THREAD

**Issue by reactiongears** [farbodsalimi/react-light-accordion#1]
First off you can't use `yarn install` because `install` has been deprecated, the command is `yarn add`. But when I use this command I don't get all the files. Only the demo folder comes though. So my react project doesn't recognize it.

**Comment by farbodsalimi** [comment]
@reactiongears Thank you for reporting the issues. I'm investigating the issues but for now, you can use `yarn add react-light-accordion@0.1.2`.

**Comment by farbodsalimi** [comment]
@reactiongears I also added a newer version `0.1.4` with updated `build` files and `README` https://www.npmjs.com/package/react-light-accordion/v/0.1.4

**Comment by reactiongears** [comment]
Thank you Sir!
